### ISSUE TITLE
[Bug] Autoloot issues

### ISSUE THREAD

**Issue by Sphaera90** [RekkasGit/E3Next#103]
Ran into a couple of autoloot issues today: 

1) Mage summoned a modrod with my looter being in in "autoloot" mode, it got stuck on cursor and stopped the looter from looting. I think Reek mentioned it previously, but autoloot is SUPER aggressive, like I have no way to effectively stop it. In Nadox I did "/bct looter //mono e3" to force stop it. Seems like it basically takes priority over any other issue/command that might arise? - should perhaps have a check or let it autoinventory stuff that for some reason ends up on cursor while looting?

2) I coth'd my looter while she was in looter mode FAR away from the corpses. She kept a corpse targeted and automatically startet "nav to target" to run loot it which was hell stopping; Hitting "Stop nav" button on the side menue thing stopped it momentarily before she started running off again. Had to /lootoff and then cancel it for it to stop. Was a bit rough while kiting with the SK > > ---- suggestion would be a possible range check? coth while in loot mode atm == bad idea

**Comment by RekkasGit** [comment]
/lootoff will now stop it, will be in the next release. 
don't coth a looter while in said mode :p
