### ISSUE TITLE
[Bug] Pet Weapons, Auto/Triggered, does not listen to /shutdown or /mono e3

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#105]
Across the board, let's sacrifice some speed for control.

It's not fun to have to wait for a completed event process / script / whatever it's called in order to get control of your toon back, when e3legacy you could simply /mqp to pause everything, instantly.

This functionality should not have been overlooked, and would only benefit the masses if this could be implemented

**Comment by RekkasGit** [comment]
Just a FYI, E3Next and Legacy work fundamentally differently. 
E3 Legacy is run by an external loop that basically dynamically executes a line of script, so what your pausing is that.

E3Next doesn't have that, as code is written as a real program not an interpreted one. 
so if there is a 'loop' created, the creator of said loop has to pay attention to certain events or its just not going to check to see if they have been executed. 

Will see what I can do to make a system that makes it easy for the developer to say "hey check for basic stuff that may kick us out"

**Comment by RekkasGit** [comment]
updates in master, soon released. please verify
