### ISSUE TITLE
[Bug] Casters constantly Manastoning through Invis application

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#106]
Makes invising anywhere extremely tedious. E3legacy, once detected invis, it ceased actions instantly, never breaking invis.

**Comment by RekkasGit** [comment]
I've added yet another invs check in the manastone code, as well as adding interrupt to spell casting in general if it detects invs. 
working on testing

**Comment by RekkasGit** [comment]
In master, try and replicate please.
