### ISSUE TITLE
[Request] Auto-evade doesn't work while disc is running

### ISSUE THREAD

**Issue by Dumot** [RekkasGit/E3Next#109]
Can remove this if statement https://github.com/RekkasGit/E3Next/blob/fd5109e6984e5b0067725b6ce633e79fd1803730/E3Next/Classes/Rogue.cs#L99

This prevents auto evade from running while a general 'burn' phase which can cause aggro to go out of control.

I've removed this statement locally and tested which worked great.

**Comment by Dumot** [comment]
Related PR https://github.com/RekkasGit/E3Next/pull/110

**Comment by RekkasGit** [comment]
merged into master
