### ISSUE TITLE
not/only functionality for /cleartargets

### ISSUE THREAD

**Issue by Sphaera90** [RekkasGit/E3Next#116]
Hello,

I would have loved a way to send /cleartargets to only certain members of the group, like the /assistMe /not|CLR functionality. 

With big AoE grinds I absolutely want my chanter + casters to keep throwing their AE's and not do anything else, but want my melee toons to keep finding new targets and melee with their FES'. 

Best regards,
//Demandred/MatC

**Comment by RekkasGit** [comment]
will be in the next release.
