### ISSUE TITLE
/ui overlay (always on top) functionality

### ISSUE THREAD

**Issue by Sphaera90** [RekkasGit/E3Next#117]
Hello again,

For the people running large monitors with /viewport black sides, it would be great if the /ui window could have an overlay/always on top check box so it can be viewed while playing EQ on single monitor. IF it's possible to make it also only be on top when an instance of EQ is the "current window" it would also be great. E.g., you tab out to browse the wiki, and don't want overlay ui windows cramping your screen, tab back and there they are... :)

Best regards,

//Demandred/MatC

**Comment by RekkasGit** [comment]
this is in master, will be deployed soon.
