### ISSUE TITLE
Looting a single item

### ISSUE THREAD

**Issue by North58Man** [RekkasGit/E3Next#119]
I would like to set the Loot.ini so only a limited # of an item will be looted. For some quests only 1 or 2 of certain items need to be looted by each toon, and trading an item does not work, they need to loot the item themselves. What I imagine is something like /lootkeep (NULL, #) where if NULL it is max stack size and if # then the max is that #.

**Comment by jonnyrocket0** [comment]
If there’s items you’re worried about looting too many of, recommend setting the item to skip and manually looting.
