### ISSUE TITLE
Mana Dump

### ISSUE THREAD

**Issue by North58Man** [RekkasGit/E3Next#122]
Can manadump be implemented. Also I am not sure if Lich and Lifetaps are working either.

**Comment by RekkasGit** [comment]
Lich and lifetaps should go into nukes/buffs. 
```
[Nukes]
Main=Ancient: Touch of Orshilak/Gem|6/Ifs|NeedHealth
[Ifs]
NeedHealth=(${Me.PctHPs}<70)
```
