### ISSUE TITLE
Abilities hitting self when using cleartargets

### ISSUE THREAD

**Issue by neflite421** [RekkasGit/E3Next#124]
When using cleartargets, I've had several instances of my zerker using one of her axe throwing abilities on herself.  My friend is having the same issue with his monk (he believes its dragon fang).  Believe it may be happening as a mob dies and they are about to do the ability but that's just a guess.

**Comment by RekkasGit** [comment]
Is this fixed?

**Comment by neflite421** [comment]
I'm not sure. I haven't played alot this past week but the few times I have
I haven't seen it happen so hopefully yes

**Comment by RekkasGit** [comment]
marking as this complete.
