### ISSUE TITLE
Autoloot not looting all corpses and looting in combat

### ISSUE THREAD

**Issue by neflite421** [RekkasGit/E3Next#125]
Autoloot often loots in combat with the general setting "Loot In Combat=False".  Also, the looter often ignores some corpses and doesn't loot them.  In mqnext this was an issue also, but you could tell the looter to loot again and they would eventually loot all the corpses.  In e3next, hitting additional looton commands does not make the looter scour for more corpses that he's already ignored.

**Comment by RekkasGit** [comment]
Loot in combat bug fixed in code on 1/1/2023, so should be in the latest release. It was case sensitive, to On/Off. I've since corrected that and it should be available via 
/ui -> Main - > Check for updates. 
There are two request in this ticket, i will look into that soon.

**Comment by RekkasGit** [comment]
deployed with v1.0.29-beta
