### ISSUE TITLE
Logging Levels for off, echo, broadcast, debug 

### ISSUE THREAD

**Issue by Atomfusion1** [RekkasGit/E3Next#131]
way to assign Write/broadcast statements to a log level and define the log level in Character Settings 
some form of: 0, 1, 2 .. where 0 = off, 1 = self echo, 2 = broadcast wide
maybe 3, or 4 for mode debug see: Command Received message etc
example/why: lets say i want to see my main Cleric and what spells shes casting in the War window i could set broadcast level 2 and see her spells but, I do not want to see bard spells at all so i set that to 0, 
could even possible add a spell /log|2 so the shaman only broadcast when casting slow
or might be nice with lifesavers to get a heads up something is going on 
i can see this getting advanced quickly but the more power you can get with minimizing spam the more likely you will be to see the information that matters

**Comment by RekkasGit** [comment]
will revisit this in the future, atm its a bit out of scope.
