### ISSUE TITLE
Mages handing out gold to pets

### ISSUE THREAD

**Issue by Littlesweetheart79** [RekkasGit/E3Next#139]
If you could add gold to the items mages out to pets.  You get the gold when you click on big spender's gold purse.  Thank you!!!

**Comment by RekkasGit** [comment]
TIL that giving gold is a thing. 
Having said that, that seems a pretty ... low on the totem pole feature to add :P

**Comment by Littlesweetheart79** [comment]
It is actual an item they equip with stats I already talked to Kemaal about it and he told me to write a ticket on here so he could do it later :-).

**Comment by RekkasGit** [comment]
A bit of an edge case, and doesn't seem Kem picked this up, so closing it.
