### ISSUE TITLE
Add Uqua gas chamber key support

### ISSUE THREAD

**Issue by jchauncey** [RekkasGit/E3Next#143]
Old e3 had support for the Uqua gas chamber door where it would tell the raid which key could be used at any given time. It does this by watching the chat of each bot and doing a `/rs` on the key that can be used next.

```
#event Define_UquaKey "#*#The #1# must unlock the door to the next room.#*#"
SUB event_Define_UquaKey(string line, string KeyToUse)
	/rs >>^<< The ${KeyToUse} unlocks the door >>^<<
	/popup >>^<< The ${KeyToUse} unlocks the door >>^<<
/return
```

**Comment by RekkasGit** [comment]
released in v1.0.33-beta
