### ISSUE TITLE
Followme Button

### ISSUE THREAD

**Issue by Littlesweetheart79** [RekkasGit/E3Next#153]
Can you make the followme button that is under the grp members work until you turn it off?  Every time you zone or stop a fight you need to click it again to make it work?  That is how the current /followme works but it would be nice to delete that button from the hotkeys and be able to use that space for something else since this button is already on the UI.

**Comment by RekkasGit** [comment]
The follow me button is part of groupinfo and not part of E3N. 
Its configured in an ini somewhere :)
