### ISSUE TITLE
/Delay for Buffs

### ISSUE THREAD

**Issue by MetalJacx** [RekkasGit/E3Next#156]
Can we add /Delay for buffs. I have an Item clicky that has a CD of 60s that not seen ${FindItem[].TimerReady} or ${FindItem[].Timer}. Otherwise I would have just wrote an If statement. 
The item cast a rune on you so in combat if it wears off before the Items CD. It will start to Spam casting the Clicky with item not ready warning spamming chat. 

This is totally the custom Items fault and not E3 so this is just a feature request if possible.

**Comment by Shenlonx** [comment]
What item? The only time I've seen behavior similar to what you're describing is when you have an attuneable item that isn't attuned.  If that's the case, attune the item to your character and it'll fix this issue.

**Comment by Shenlonx** [comment]
Talked to MetalJacx and they confirmed timers are displaying correctly after attuning, closing issue.
