### ISSUE TITLE
No UIs open from MQ2 or plugins

### ISSUE THREAD

**Issue by Gnogaine** [RekkasGit/E3Next#161]
I'm a brand new user.  First time installing was on Feb 17

Starting Feb 19, I can't get any UIs to open and after days of troubleshooting, I'm at a loss.  E3UI.exe still runs, but any of the UIs drawn in-game from MQ fail.
Autologin, /mqsettings, opening console via hotkey (CTRL+`), MQ2Nav, /mqoverlay, etc... all fail to show any window.

My MacroQuest logs mention "IDirect3DDevice9" and "MQOverlay" activities until the night of 2/19, then no logs after that show those activities.
Last logs from when UIs worked:
[MacroQuest-20230220T023305.803121Z.log](https://github.com/RekkasGit/E3Next/files/10832578/MacroQuest-20230220T023305.803121Z.log)

Logs from later the same night that don't show any UI activity:
[MacroQuest-20230220T025939.059067Z.log](https://github.com/RekkasGit/E3Next/files/10832585/MacroQuest-20230220T025939.059067Z.log)

I've tried:
-Resetting all configs to default
-Downloading a fresh copy of this compile and using it with no customizations
-I've tried looking for mentions of EQGame.exe or any related .dll files in the registry at "HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers", but nothing is there.
-Issue persists when running completely separate compiles (like MMOBugs)
-I've uninstalled and reinstalled all C++ redistributables
-I've installed the x86 June 2010 DirectX SDK in hopes that getting access to d3d9.lib and d3d9.h may help with whatever's going on, but I don't know enough about it to begin to know where to put them.

There's plenty more that I've tried that I may be forgetting, but at this point I'm sure it's something specific to my machine, but I'm not really sure where to go next.  I appreciate any kind of insight/help anyone can provide!

**Comment by Gnogaine** [comment]
To add to this, I've also confirmed that the issue only affects one EQEMU build/server.  Other servers load fine with the same MacroQuest config.

**Comment by RekkasGit** [comment]
I am sorry I am unsure how to address this, as it does seem something is broken in your install :\

**Comment by Gnogaine** [comment]
No worries.  It was definitely something broken with my server install.  Couldn't track down the actually offending files, so I grabbed an outdated copy and was able to get back up and running with that.

Thanks!
