### ISSUE TITLE
/grez issue

### ISSUE THREAD

**Issue by neflite421** [RekkasGit/E3Next#165]
When using /grez with Blessing of Resurrection as the rez spell,  the cleric will rez himself first and doesnt accept it which is fine, but then as he cycles through the group members waiting for the cooldown he usually ends up back on himself and tries rezzing himself again.  If you wait long enough eventually he'll get some others but seems like he tries re-rezzing himself most of the time.

**Comment by RekkasGit** [comment]
I have it now waiting up to 6 sec for the rez ability.  (current)
I have also changed it to the rezer will rez thsemselves last.  (next update)

However default 12 sec cooldown puts the rezer in the rez loop for a long time, i would suggest stacking the rez. 

```
AutoRez=Off
Auto Rez Spells=Token of Resurrection
Rez Spells=Blessing of Resurrection
Rez Spells=Water Sprinkler of Nem Ankh
```
The rez yourself last will be in the next update, the above config works now.
