### ISSUE TITLE
[Feature Request] Command to show saved groups

### ISSUE THREAD

**Issue by allhopeislost** [RekkasGit/E3Next#168]
Currently you can only see saved groups in the .ini
Would be nice to have a command like /savedgroups or /listgroups to see your saved groups.

**Comment by TheVons** [comment]
Does this look helpful?

![image](https://user-images.githubusercontent.com/26316029/229420928-75c418fb-c651-4cd9-9b51-c74128c71a6f.png)

**Comment by TheVons** [comment]
I suppose I could filter it for just the server you are on. I can work on that tomorrow if you think this is going in the right direction?

**Comment by TheVons** [comment]
![image](https://user-images.githubusercontent.com/26316029/229423054-1e9b1353-26b9-44ce-aa53-ca49b6b02582.png)

**Comment by TheVons** [comment]
https://github.com/RekkasGit/E3Next/pull/170

**Comment by allhopeislost** [comment]
Yeah that would work. I might be easier to read if done like this
[example group 1] <purple
member1 <green
member2
member3
etc
[example group 2]
member 1
member 2
etc

No need to add  Group Name and Members: to each group in the list that way.
Can also make a generic mention on how to load groups, so you also don't need to add that line for every group.

**Comment by TheVons** [comment]
I am slacking but have not forgotten about this.

**Comment by TheVons** [comment]
This PR is waiting for acceptance

**Comment by RekkasGit** [comment]
will be in the next release
