### ISSUE TITLE
[Feature Request] Manastone Customization at Character Level

### ISSUE THREAD

**Issue by Elrindil** [RekkasGit/E3Next#171]
Currently the manastone function is set at the global level to either happen or not on all characters.  Simple solution is to remove a manastone from anyone that might have it that you don't want it to trigger on.

Was looking to have the [Manastone] variables be set at the character ini lavel so that you could customize what %'s each character type will fire their manastone.  This is a very low priority and one that might not be needed by others.

**Comment by RekkasGit** [comment]
will be in the next version
