### ISSUE TITLE
Update to Magician Buff coding based on new patch notes.

### ISSUE THREAD

**Issue by Klokworkk** [RekkasGit/E3Next#177]
With the update to the patch notes.  Rather than have the Magician Cast "Grant Spectral plate" and heirloom on himself and unfold it, then give to pet.  Can we now have mage just Cast Grant Spectral Plate and Grant Enibik's Heirlooms directly on the requesters pet?  The handing out of Weapons would remain unchanged.  From Patch notes:

 Gnock — 05/04/2023 9:16 AM
-- Magician: Grant Spectral Plate and Grant Enibik's Heirlooms can now be cast with a pet on target for it to directly equip the gear.

**Comment by RekkasGit** [comment]
I think this got updated?
