### ISSUE TITLE
[Feature Request] - specify zones to disable manastone checks

### ISSUE THREAD

**Issue by Freigther** [RekkasGit/E3Next#184]
Would be great if there could be an added line to the manastone section where users could specify zones to exclude manastone from toggling. So that toons won't attempt to spam manastone in zones where servers have disabled their use, or do not wish for them to be used.

More a QOL request so users do not have to keep editing inis.

Many thanks, much appreciated!

**Comment by RekkasGit** [comment]
okay, made this editable in the character manastone section.
![image](https://github.com/RekkasGit/E3Next/assets/4657161/10138490-f20c-47b2-a98c-21eeb07d8a6f)
