### ISSUE TITLE
E3UI Not Closing

### ISSUE THREAD

**Issue by MetalJacx** [RekkasGit/E3Next#202]
With the old /ui command, you could run /ui to close it again. With /e3ui this seems to not be the case and doesn't close.
Also when I hit hide, it is gone and /e3ui won't bring it back up. Had to do /mono e3 to reset everything.

**Comment by RekkasGit** [comment]
/e3ui is a toggle which should hide/show, if you wish to 'kill' the ui, you can do /e3ui-kill
