### ISSUE TITLE
Issue with AoE range

### ISSUE THREAD

**Issue by Zarius01** [RekkasGit/E3Next#203]
In testing with the ENC/CLR spell Wake of Tranquility (AoE ranged pacify) E3N is reporting that the target is out of range when it is not.

Standing in the exact same position for both below tests I receive the following results.

**Result 1** using E3N with the following command ```/nowCast CharacterName "Wake of Tranquility" ${Target.ID}```
I receive the following response in the MQ Window: ```<CharacterName> Nowcast of Wake of Tranquility unsuccessful due to CAST_OUTOFRANGE!"```

**Result 2** casting direct from the character
Casting directly from the enchanter standing in the exact same position the cast is successful and the mob(s) are pacified when clicking the spell gem rather than using the nowCast command

The Wake spell is a 200 spell range, but has a 30 or so AoE effect range.  Is it possible that MQ/E3 is assuming the value of the AoE effect, rather than the actual cast range when attempting to cast the spell?

Thank you.

Zar.

**Comment by MetalJacx** [comment]
I believe I know the issue. Wake of Tranquility is consider a beneficial spell and not detrimental so the check is not leveraging range and automatically leveraging AE Range.

![image](https://github.com/RekkasGit/E3Next/assets/13805973/ace2e3f5-58ee-4e9b-b13e-becdca358845)

`if (SpellType.Equals("Detrimental", StringComparison.OrdinalIgnoreCase))
                    {

                        if (AERange > 0)
                        {
                            if (MyRange == 0)
                            {
                                //set MyRange to AE range for spells that don't have a MyRange like PBAE nukes
                                MyRange = AERange;
                            }
                        }

                    }
                    else
                    {
                        //if the buff/heal has an AERange value, set MyRange to AE Range because otherwise the spell won't land on the target
                        if (AERange > 0)
                        {
                            MyRange = AERange;
                        }

                    }`

i think maybe adding a subcategory check for CALM, might fix this issue.

![image](https://github.com/RekkasGit/E3Next/assets/13805973/98029f8c-ba8f-4a72-aef1-13a428bd637e)

**Comment by MetalJacx** [comment]
Bug fix submitted and waiting for verification and merge approval.
