### ISSUE TITLE
HealOverTime function of the Heal.cs doesn't utilize CheckFor functionality

### ISSUE THREAD

**Issue by MaterousApps** [RekkasGit/E3Next#206]
When utilizing the CheckFor functionality in the HealOverTime section of the INI, it doesn't actually work.  It will continue to try and cast the HoT multiple times on the target, when a higher level HoT is already present.  This is noticable when using a Shm (Breath of Trushar) and a Druid (Celestial Healing).

If the Shaman lands a Breath (or the druid already had a Celestial Healing), the druid will continue to try and cast the HoT, even though it doesn't take hold.

This is the line in the inis:
SHM - Heal Over Time Spell=Breath of Trushar/Gem|2/HealPct|85/NoInterrupt/CheckFor|Celestial Elixir
DRU - Heal Over Time Spell=Celestial Elixir/Gem|2/HealPct|80/CheckFor|Breath of Trushar

This can be fixed by adding the following code (copied from the Heal function in Heal.cs) to the HealOverTime function:

```
bool shouldContinue = false;
  if (spell.CheckForCollection.Count > 0)
  {
      var bufflist = E3.Bots.BuffList(name);
      foreach (var checkforItem in spell.CheckForCollection.Keys)
      {
          if (bufflist.Contains(spell.CheckForCollection[checkforItem]))
          {
              shouldContinue = true;
              break;
          }
      }
   if (shouldContinue) { continue; }
}
```
This was added right after line 740 and right before the recastSpell tag. I have been using this code all day and it functions without any errors and proved to work exactly as expected.

**Comment by MetalJacx** [comment]
Changes made, waiting for approval and update release to merge.
