### ISSUE TITLE
Cleric disconnecting while rezzing many corpses in raids

### ISSUE THREAD

**Issue by Dumot** [RekkasGit/E3Next#214]
Notice this past couple weeks. The cleric will go link dead when trying to cycle through rezzing a lot of dead players.

**Comment by jonnyrocket0** [comment]
Will need you to provide some proof of this. I have never heard of this complaint, and autorez has been out for the life of e3n

**Comment by Dumot** [comment]
I'll try and get some. Multiple of our DSK team experience this in DSK.

**Comment by Dumot** [comment]
So we raided DSK/fippy again and it happened again to a couple of us. The general consensus is that it's when they're auto rezzing and toggling through corpses.

I am doing an Anguish run now and it happened while i was watching the cleric. It indeed was just going through the whole group telling everyone to wait4rez, cycling through corpses then went link dead
![Screenshot 2024-02-08 111404](https://github.com/RekkasGit/E3Next/assets/121333614/0f241865-a1ce-49a8-bb82-3881ee280593)

**Comment by Dumot** [comment]
This has been fixed as of who knows when but it's not happened since i've come back.
