### ISSUE TITLE
Implement in-game spell swapping functionality

### ISSUE THREAD

**Issue by porkchop520** [RekkasGit/E3Next#223]
In "old" e3 you could send a tell or group message containing spellset <name> in order to get your characters to change spell sets while in game. This gave great flexibility on a per encounter basis for casters while in game.

**Comment by RekkasGit** [comment]
you can swap entire config files in E3N just a FYI. 

/e3reload "fire"

will copy your current settings if "fire" doesn't exist and then you can edit it and set it up however you like.  To go back to your normal, just do /e3reload without a param

**Comment by RekkasGit** [comment]
tho I do see a downside as the first time a spell is required, i will slot that spell in the proper gem slot thus initial attack might be a bit . 'slow' when toons mem their pells. I will see about that part.

**Comment by RekkasGit** [comment]
okay, now whenever you do an e3reload, it will do a spell memorization of the new ini. 
I have also greatly improved the memorization. This is in my current development branch, so should be available  in the near future.
