### ISSUE TITLE
Add spell flags to handle fizzle logic for non-heals

### ISSUE THREAD

**Issue by SAR-2019** [RekkasGit/E3Next#228]
It would be handy to have fizzle logic available for spells similar to following;

[Debuffs]
Debuff on Assist=Mark of Karn/Gem|4**/RetryFizzle**/AfterSpell|Unswerving Hammer of Faith

[Debuffs]
Debuff on Assist=Mark of Karn/Gem|4/AfterSpell|Unswerving Hammer of Faith**/RetryFizzle**

If one flag can be used that would be economical, but if different flags need to be used due to the underlying code that would be fine as well, e.g. 

Base Spell = /RetryFizzle
AfterSpell = /RetryASFizzle
BeforeSpell = /RetryBSFizzle

**Comment by jonnyrocket0** [comment]
I understand this optimization but I’m not sure it’s worth it. If the spell fizzles, it will try to cast again the next debuff loop. Fizzling is eventually eliminated with aa’s as well

**Comment by RekkasGit** [comment]
I think most of this about before/after spell and the way it simply tries once

**Comment by RekkasGit** [comment]
But agreed, it is mostly handled by skill level and AAs

**Comment by SAR-2019** [comment]
That's right, mainly for Afterspell/Beforespell.

AA's are great and you're correct they do handle this problem however they don't come into the picture until higher levels which generally means a run from 1-60 without these AA's, and I believe the fizzle elimination AA is only available to Bards+Casters (not priests or any other class). I've found reference to "Spell Casting Mastery" "reducing" fizzles however on my server the AA description doesnt mention this at all.

**Comment by RekkasGit** [comment]
I have changed it in my branch to just retry fizzles on before/after and be done with it :)
