### ISSUE TITLE
[Feature Request] Ramp Target Tracking

### ISSUE THREAD

**Issue by Dumot** [RekkasGit/E3Next#241]
Could we add the ability to track who's on rampage? I noticed the filtering now displays rampage message so i feel like this should be in the realm of possibility. 

 Perhaps if there were some var e3 tracks then we could interact with in if statements to take actions while being targeted. Or even if it's target a/your pet too, then you could react accordingly.

**Comment by RekkasGit** [comment]
was added to the current release.
