### ISSUE TITLE
[Feature Request] Remove jokes and facts from e3discord

### ISSUE THREAD

**Issue by zenj0** [RekkasGit/E3Next#246]
E3Discord is amazing but the hourly jokes and facts is a bit much. Is it possible to add a toggle to turn them off or remove them entirely? Thank you!

**Comment by jonnyrocket0** [comment]
Yeah I can add this. I may just take it out altogether; it was just a trolly thing I added when I was proving it out and never removed itSent from my iPhoneOn Jul 8, 2024, at 5:42 PM, zenj0 ***@***.***> wrote:﻿
E3Discord is amazing but the hourly jokes and facts is a bit much. Is it possible to add a toggle to turn them off or remove them entirely? Thank you!

**Comment by zenj0** [comment]
> Yeah I can add this. I may just take it out altogether; it was just a trolly thing I added when I was proving it out and never removed itSent from my iPhoneOn Jul 8, 2024, at 5:42 PM, zenj0 ***@***.***> wrote:﻿ E3Discord is amazing but the hourly jokes and facts is a bit much. Is it possible to add a toggle to turn them off or remove them entirely? Thank you! —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Nice, thanks much!

> Yeah I can add this. I may just take it out altogether; it was just a trolly thing I added when I was proving it out and never removed itSent from my iPhoneOn Jul 8, 2024, at 5:42 PM, zenj0 ***@***.***> wrote:﻿ E3Discord is amazing but the hourly jokes and facts is a bit much. Is it possible to add a toggle to turn them off or remove them entirely? Thank you! —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Nice, thanks!

**Comment by RekkasGit** [comment]
updated in master
