### ISSUE TITLE
[Feature Request] Check for blocking windows before casting a spell

### ISSUE THREAD

**Issue by Random-ice** [RekkasGit/E3Next#252]
Some windows, when they are open, block casting of spells. Such as Bank, Merchant, Tribute Master. (there may be others, but I check a bunch and so far these 3 are the ones I know about)

Request: Before doing a cast of any spell check if any of these blocking windows are open, and if so cancel the cast and echo a message.

**Comment by RekkasGit** [comment]
agreed, pushed code into master
