### ISSUE TITLE
Driver will continue to nuke corpses when the mob is dead.

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#28]
Driver will continue to nuke corpses when the mob is dead.

**Comment by RekkasGit** [comment]
I believe I have made an improvement for that, please test :)

**Comment by r33kgr3yj0y** [comment]
Seems to lockup less, still having the problem.

Forgive the ignorance, it almost feels like they finish out their rotation, in terms of like the Advanced Settings, like, if they're on 3, they'll finish all the way down on the current target even if it's dead. Most of the time i need to /backoff to end combat / change targets.

**Comment by RekkasGit** [comment]
Issue seems to be mostly resolved
