### ISSUE TITLE
Feature Request: Add /gathercorpses command from e3 legacy

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#39]
/gathercorpses was a command, when issued, would have the caller say /raidsay Consent Me and then each toon in the raid would consent the caller, and the caller would drag every corpse in radius.

**Comment by RekkasGit** [comment]
I believe this feature was just added by Kem, test it :)

**Comment by jonnyrocket0** [comment]
Added /gathercorpses command that will request consent and drag all within 100 units to you. Added chat event handler to grant consent.
