### ISSUE TITLE
Wait4Rez not working correctly

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#41]
In combat, I execetued an /aerez from Cleric

Wizard got Wait4Rez tell, but did not auto accept / loot corpse.

Reproducable by dying in combat and rezzing a target in combat.

**Comment by r33kgr3yj0y** [comment]
when i did /rezit from my tank, he used a Rez token, and the target successfully looted their corpse. This was out of combat

**Comment by RekkasGit** [comment]
This is probably because assistme would reset the wait4rez. I have removed it from assistme though its still on followme.
