### ISSUE TITLE
Driver / Shadowknight memorized spell in the middle of a multi-mob fight

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#47]
i was just in the middle of a named fight, got an add, the add died, and the Driver/Knight thought it was a good time to mem a spell, sat down, and got rounded by the still-alive named. 

would love this to be addressed as it just caused a wipe

**Comment by RekkasGit** [comment]
Not to be obtuse... but just don't have a spell setup to in combat buffs that you would have to mem? :)

**Comment by RekkasGit** [comment]
What is the setup that caused this to happen?

**Comment by r33kgr3yj0y** [comment]
It wasn't a combat buff, it was a Self Buff, Cloak of Discord. 

Fighting 4 mobs. Mob 1 dies, SK goes "hey my self buff is down, and the mob is dead, now is the perfect time to reapply my self buff" Sits, takes full damage, dies.

**Comment by RekkasGit** [comment]
Pushed a fix, it was checking for Assisting instead of InCombat.
