### ISSUE TITLE
Tell Relay is gone

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#49]
Tell relay is no longer functional

**Comment by r33kgr3yj0y** [comment]
how can we prevent these changes from being overwritten in the future? First the druid cheetah (which was fixed, thank you) but now this

**Comment by jonnyrocket0** [comment]
There was a general setting added to toggle this feature. Sorry for not communicating it.

Relay Tells (On/Off)=Off
