### ISSUE TITLE
Make /assistme call everyone on EQBC

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#50]
For testing purposes, and to line up with e3legacy, it would be preferred to have the /assistme and all associated battle commands to hit the whole EQBC. Also, a tag "GRP" should be added to only/not to support functionality as follows in examples:

/assistme /only|GRP
/assistme /not|DRU ENC

**Comment by RekkasGit** [comment]
/assistme "/not|DRU ENC"
works now, unsure how I feel about broading to everything in eqbc, as it will send to your other toons that are not part of your group. 

I think I would rather add an /all flag, to broadcast it out to all instead of group. more of an opt in, thoughts?

**Comment by RekkasGit** [comment]
I've added /all but not much testing, please test.

**Comment by RekkasGit** [comment]
backoff, assistme, followme, follow now allow the /all option.
