### ISSUE TITLE
Again: Combat buffs being cast in combat, not during assistme

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#55]
There was a fix weeks ago about not casting in COMBAT BUFFS in COMBAT, but only during ASSISTME.

Somehow this change got reverted with another pull I did. I don't know when it got messed up but it's been a few days now.

Desired Functionality: Do not cast combat buffs unless you are IN COMBAT and ASSISTME is called. Don't know how this got changed / reverted as it was 100% fine before. (if it aint broke dont fix it)

**Comment by RekkasGit** [comment]
Combat buffs are now only called if the InCombat Returns true. 
This returns true if. ...
 bool inCombat = Assist.IsAssisting || _mq.Query<bool>("${Me.Combat}") || _mq.Query<bool>("${Me.CombatState.Equal[Combat]}");

**Comment by RekkasGit** [comment]
issue resolved, now combat buffs will not cast if you are moving/naving/etc.
