### ISSUE TITLE
AutoRez / Wait4Rez / corpse recovery does not check for multiple self corpses

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#57]
Currently, the Wait4Rez routine, checks for 1 corpse, then thinks its done. 

A check to make sure there are no other Self Corpses to loot is required

**Comment by RekkasGit** [comment]
they do check for other corpses, but will not loot corpses that can still be rezed. Or at least that is the way I originally thought of it.

**Comment by jonnyrocket0** [comment]
I have personally seen this work. Needs more info to prove there's a bug here
