### ISSUE TITLE
Azure Stones / Mod rods in combat only

### ISSUE THREAD

**Issue by merrittous** [RekkasGit/E3Next#60]
Please. Cherry on top. my poor enchanter and mage cannibalize themselves when each has to summon them

**Comment by RekkasGit** [comment]
![image](https://user-images.githubusercontent.com/4657161/209425836-4fd538d4-e6b1-4a93-8d53-d8818a51c7cb.png)

Already an option :) just set this to "Off" on the proper character that is supplying.
