### ISSUE TITLE
Familiar Killer.

### ISSUE THREAD

**Issue by merrittous** [RekkasGit/E3Next#61]
I have a private code that auto "/pet get lost" on familiars of every type. Can we implement something similar?

**Comment by RekkasGit** [comment]
sure , post the macro code and we can see about converting it.

**Comment by Shenlonx** [comment]
In the meantime, I use MQ2React to solve this problem with the following react:
```
  RemoveFamiliar: 
    action: /pet get lost
    condition: >-
      ${Select[${Me.Pet.Class},banker,merchant]}==0 && (${Me.Pet.Name.Find[familiar]}>0
      || ${Me.Pet.Level}==1)
```
Works great and doesn't dismiss the pets summoned by the veteran AAs that summon vendors/banker.

**Comment by RekkasGit** [comment]
why not just use an after event?
