### ISSUE TITLE
Feature Request / Bug: Auto Follow is disabled when Auto Looting

### ISSUE THREAD

**Issue by Dumot** [RekkasGit/E3Next#64]
When a toon has Auto Loot enabled they will go to loot but just stand there as auto follow is turned off to loot but not turned back on.

Previously the looter would go to loot the corpse(s) then resume following.

Granted this is accomplished by using the Anchor feature it would probably be convenient to those who still use follow to retain this functionality.

**Comment by RekkasGit** [comment]
pushed a fix in "v1.0.19-beta"

**Comment by Dumot** [comment]
Confirmed as now working.
