### ISSUE TITLE
[Bug] AutoRezzer will keep targeting corpse until it's looted

### ISSUE THREAD

**Issue by Lyricalpanda** [RekkasGit/E3Next#66]
Had a toon set to AutoRez my tank. Tank crashed loading into zone from rez. Toon rezzing kept switching targets back to the corpse that was being rezzed until it was looted.

Tried several times to call assistOn from rezzer itself. Immediately after, rezzer would switch back to corpse it had already rezzed (but not looted)

**Comment by RekkasGit** [comment]
the target is because the rezer is trying to determine if the corpse can be a valid rez. 
This requires a target and /consider.
this will not impact the healer in any way as they will retarget you to heal.
