### ISSUE TITLE
[Request] Make burns only fire for a short time after being called

### ISSUE THREAD

**Issue by Lyricalpanda** [RekkasGit/E3Next#67]
Reek: When you call LongBurns (or any burn for that matter), deactivate after 30s. as in, if im in a 5 minute fight, and i hit LongBurns in the first 10 seconds, at 4m45s , burns come back up and fire... it would be very futurey-e3-nexty to up the intelligence in this logic

**Comment by RekkasGit** [comment]
Done, should be in the next release.
