### ISSUE TITLE
[Bug] Aerez keeps trying to rez bodies without consent

### ISSUE THREAD

**Issue by Lyricalpanda** [RekkasGit/E3Next#70]
![image](https://user-images.githubusercontent.com/1665885/209475760-55510a20-13ce-4e79-9f25-4447d538277d.png)

**Comment by RekkasGit** [comment]
Steps to reproduce? 
Consent doesn't matter, it will "Try" and /corpse the body, but will rez it anyway. 
Its all about if /consider says the corpse is resurrectable or not. 
"This corpse can be resurrected"

**Comment by RekkasGit** [comment]
Closing until more info is given.
