### ISSUE TITLE
[Bug] Aerez - naked cleric having issues rezzing

### ISSUE THREAD

**Issue by Lyricalpanda** [RekkasGit/E3Next#71]
![image-1](https://user-images.githubusercontent.com/1665885/209475809-ced40da1-63f3-4851-98ee-7156a125c30f.png)

Reek: "and the cleric doesn't accept it's own rez"

**Comment by RekkasGit** [comment]
have an update about accepting rez, its in mater.

**Comment by RekkasGit** [comment]
recheck, closing for now.
