### ISSUE TITLE
[Request] Only use certain spells for aerez

### ISSUE THREAD

**Issue by Lyricalpanda** [RekkasGit/E3Next#72]
Reek: i'd also like the ability / choice for my cleric on auto rez to **never** mem a rez spell. Wait the cooldown if you're naked, or, how about this, loot your damned corpse. what is the logic for a cleric auto rezzing to never take the rez and loot themselves first? that's how it's done back in the day

**Comment by RekkasGit** [comment]
I think we should make this optional to pass in the list of rez spells instead of just using the hard coded list.

**Comment by RekkasGit** [comment]
completed.
