### ISSUE TITLE
Feature Request: CheckFor added to QuickBurns

### ISSUE THREAD

**Issue by Dumot** [RekkasGit/E3Next#74]
Please add checkfor and any other options to the Quickburns section.

Context: 
Ranger can cast Group Guardian but when using Guardian they cannot check to wait until group guardian fades before attempting to cast it.
Another, Rogue can't wait for Cry Havoc to end before using Third Spire

**Comment by RekkasGit** [comment]
in process

**Comment by RekkasGit** [comment]
Done should be in the next release
