### ISSUE TITLE
[Request]  Generic commands to fire with if statements in INI

### ISSUE THREAD

**Issue by Lyricalpanda** [RekkasGit/E3Next#75]
Lazaus discord MetalJacx:
```
[CMD]
AutoCMD=On
Command1=/g hello
Ifs1=Combat
Command2=/g goodbye
Ifs2=Boss
Command3=/g i am nuetral
Ifs3=TRUE
[IFS]
LowHP=${Target.PctHPs} <= 20
Named=${Target.Named}
Boss=${SpawnMaster.HasTarget}
Combat=${Me.Combat}
```

![ini](https://user-images.githubusercontent.com/1665885/209488349-661e9f4a-65e5-4fc5-a048-870a9c5eb1b1.PNG)

Link to convo: https://discord.com/channels/548643730714918913/1024676514119290901/1056683414956294234

**Comment by r33kgr3yj0y** [comment]
Seems like this would make afk exp really easy

**Comment by MetalJacx** [comment]
> Seems like this would make afk exp really easy

I would have to respectfully disagree. It would take more then slash command and if statement to automate. With the allowance of private code and old E3 just being macroquest I feel that would be the bigger concern if you worried about afk.

**Comment by r33kgr3yj0y** [comment]
Pick target

/nav target

Anchor back 

/Cleartargets
You say it's not simple, but i disagree

**Comment by MetalJacx** [comment]
I will give you that logic is simple, but afkable not at all. Without logic around pull range, return to camp, chase logic, when you should med, etc. I would not walk away from my computer. I mean it nothing people couldn’t do already in E3 if they already wanted it.

**Comment by r33kgr3yj0y** [comment]
That's all surmountable with current ini settings. It's really up to the coders what they want in or not, I just wanted to shed light on what's potentially a future issue

**Comment by MetalJacx** [comment]
No problem respect. Hope I didn’t come off argumentative.

**Comment by jonnyrocket0** [comment]
We will not be implementing this.
