### ISSUE TITLE
[Request] Enable NowCast/QueueCast to utilize /ifs

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#77]
basically, to nowcast Turn Undead only if target is undead, and of course however else this can be utilized.

Thank you for your time.

**Comment by jonnyrocket0** [comment]
Can’t you already accomplish this via `/nowCast Healies “turn undead /ifs|${Target.Body}==Undead”`

**Comment by RekkasGit** [comment]
Done should be in the next release
