### ISSUE TITLE
[Bug] Bard melodies with singular songs

### ISSUE THREAD

**Issue by Lyricalpanda** [RekkasGit/E3Next#78]
There's an issue if you use a melody with a singular song, such as selos song of travel or selos accelerating chorus.

Link to recent discussion:

https://discord.com/channels/548643730714918913/1024676514119290901/1056973980612952165

For now, workaround is to playmelody stop, nowcast bard song.

**Comment by jonnyrocket0** [comment]
what is the problem you're seeing? i set up a single song melody to test and it behaved exactly as i expected 
![image](https://user-images.githubusercontent.com/19800293/209984466-3317cf99-c7d4-49fc-8807-fdbc3f678dd6.png)

**Comment by RekkasGit** [comment]
They don't want it to twist.

**Comment by RekkasGit** [comment]
single song twists should now work.
