### ISSUE TITLE
[Bug] Assiston melee not following target consistently

### ISSUE THREAD

**Issue by Lyricalpanda** [RekkasGit/E3Next#83]
Latest pull on main seems to have issues with assistOn for melees. I've had melees that are positioned slightly incorrect - they're in range of the target, but not facing the target. Other times, they don't stick to the target if the target moves.

Examples:

![notAssisting](https://user-images.githubusercontent.com/1665885/209603983-bfe17755-49e5-437f-b97f-4a790eed78ce.PNG)

Here, I dragged the mob from the original /assistOn command. Shugs is where the mob originally was. When I dragged the mob, Hilsud and Dalas correctly followed the mob. Shugs did not. I called /assistOn again, and Shugs would not reposition to be in range of target.

![hmmm](https://user-images.githubusercontent.com/1665885/209604029-d5f9b265-728f-4dd6-8666-ccec83965185.PNG)

Here, Hilsud is in range of the mob, but is angled incorrectly so it cannot attack (`You cannot see your target` messages since wireframe is on).

Seems like /assistOn is not properly allowing toons to always follow mob/reposition if mob turns, and not properly allowing subsequent /assistOn calls to force a reposition on target.

Note, /assistOn with a new target will have all toons properly start in range on the mob and facing it.

**Comment by RekkasGit** [comment]
e3 doesn't keep the toon close to the mob, thats the job of the /stick command. 
![image](https://user-images.githubusercontent.com/4657161/209604684-caa8b75e-629b-4cc5-ae18-6e320aaad87a.png)
When we recieve the "Your target is too far away, get closer!", we reduce the stick distance and recall stick .
![image](https://user-images.githubusercontent.com/4657161/209604756-c6b4be2f-335f-4705-90dc-0054c4613d74.png)


Now, there is no code for 'you cannot see your target' and that may be something that needs to be addressed.

**Comment by RekkasGit** [comment]
I personally don't have a melee team , so will defer to shen/kem on this situations.

**Comment by RekkasGit** [comment]
Also note, multiple assistOn are ignored if currently assisting. The command simply ignored. 
backoff -> assistme, would work tho.

**Comment by Shenlonx** [comment]
How consistent are you seeing this happen? I've seen issues occasionally with my melee toons, but I'd say extremely infrequently. 

Also, can you post your melee [Assist Settings] if they differ from these settings:

[Assist Settings]
Assist Type (Melee/Ranged/Off)=Melee
Melee Stick Point=Behind
Melee Distance=MaxMelee

**Comment by Lyricalpanda** [comment]
I was able to repro this on each mob I tried it on in cazicthule with kem once I noticed it. I'll try again later tonight, but seems pretty consistent if you drag the mob after calling /assistOn or turning it

**Comment by Lyricalpanda** [comment]
Although I did just switch from running background fps to frame limiter, wonder if that's causing some issues with /stick? I'll do some more tests around that as well

**Comment by Lyricalpanda** [comment]
Tested in Crushbone, with the following situations:

1)
background FPS (settings) minimum
framelimiter: enabled on background, 1FPS, simulated 60FPS

2) background FPS (settings minimum)
framelimiter: enabled on background, 30 fps, simulated 60FPS

3) background FPS (settings) 30
framelimiter: disabled on background

I was still able to repro in all three situations, although it may be with background set to 30 fps it seemed harder to repro (could have been luck). Crushbone was easier to repro, but I was still able to get consistent results constantly whiplashing the mob. Although this is sounding like an outside issue possibly with /stick.

https://media.giphy.com/media/xCiVAG5pbhNwaF07gU/giphy-downsized-large.gif 
oof that's one pixelated gif. But can see 2/3 melees no longer properly /sticking at the end.

**Comment by RekkasGit** [comment]
I've made an update to add another check for "You cannot see your target." for melee to redo stick. 
can you test and see?

**Comment by Lyricalpanda** [comment]
Sure, I'll do the test later today. Thanks for the update.

**Comment by RekkasGit** [comment]
no update, closing till more info.

**Comment by Lyricalpanda** [comment]
I was able to see restick on "You cannot see your target" work a few times yesterday between LDONs and even in oasis. So that part is working 👍 

I haven't tried to test around dragging the mob after calling assist to trigger a "You are too far from your target" type of message.

As a side note, I'm not sure why in e3next assisting isn't consistently in the back of the mob. In legacy E3, the assists will consistently stay on the back side. I'm seeing that my melee will be maybe 30-45 degrees off from the back most of the time, and some of the assists are just on the side/in frontal cone of mob.
