### ISSUE TITLE
Auto-assist not working

### ISSUE THREAD

**Issue by allhopeislost** [RekkasGit/E3Next#84]
Currently auto-assist is not in the E3-next release.
I kinda liked that E3 feature, hope you can bring it back!

**Comment by RekkasGit** [comment]
I didn't implement it at the time because.. well I don't use it :) Nor does anyone else on the testing/dev group. 
however I *know* people like it, and that it *should* be added for those. 
Even tho it sets a bad habit =p

Its now on the todo, however. Ty.

**Comment by RekkasGit** [comment]
done
