### ISSUE TITLE
[Bug] Toons will manastone themselves out of invis

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#85]
Finsished a named fight, invis since pather was coming, wizard manastoned herself out of invis, tagged aggro.

Detect invis? instantly stop manastoning / casting

**Comment by RekkasGit** [comment]
![image](https://user-images.githubusercontent.com/4657161/209695900-9ee052ed-517a-4053-b25a-6f4b6da4a1c4.png)
it already checks invs, possibly it was past that check when you invised them?

**Comment by RekkasGit** [comment]
I will add another check in the manastone loop itself

**Comment by RekkasGit** [comment]
pushed, test pls

**Comment by RekkasGit** [comment]
closing for now, unless said otherwise.
