### ISSUE TITLE
[Request] Add follow range to /chaseme and /followme

### ISSUE THREAD

**Issue by allhopeislost** [RekkasGit/E3Next#90]
Currently the /chaseme and /followme command follow you really closely. 
I rather have them a bit further back. It would be nice to be able to specify a follow range.
The current short range also kinda interferes with looting. After the mob is dead, the looter first comes back to the followchar and then goes back to the corpse for looting.

**Comment by Shenlonx** [comment]
Added Min and Max Chase distance as well as NavStopDistance to the General Settings under [Movement]. Doesn't look like /afollow has any allowance for modifying the distance that a toon follows that I'm seeing, but Min Chase Distance will keep your toons from chasing you until they exceed that threshold and Max Chase distance will keep them from trying to chase you if you go over that threshold (like you get summoned and forgot you had chase on).

NavStopDistance will modify the NavToSpawn function to stop within the specified distance of the target. Note that you may have to play with the distance a bit as they won't necessarily stop on a dime at the specified distance, it's just that once they are within that distance from the target, they will stop nav next time nav does it's position update check.

**Comment by allhopeislost** [comment]
Sounds very nice. Will try it out when the next releases gets pushed.
