### ISSUE TITLE
[Enhancement] Make buffs recast before they expire

### ISSUE THREAD

**Issue by r33kgr3yj0y** [RekkasGit/E3Next#97]
Maybe 30/60/90s whatever you think is best, it is just a little frustrating then the stars allign and a bunch of buffs wear off at once, vs recasting them prior to expiration.

Thanks for the consideration

**Comment by RekkasGit** [comment]
maybe a general option?

**Comment by Shenlonx** [comment]
I think the best case for this is a /MinDuration flag on a per spell basis, so you can tailor the duration you want to maintain based on the spell, and some of them like Boon of the legion leave a real tight window for keeping it up on multiple targets. 

Or maybe a general option with allowing /MinDuration to override for the special cases where it matters more.

**Comment by jonnyrocket0** [comment]
i think rather than adding yet another option for people to keep track of, make buffs recast at a set duration. some options could be: 
- the spell cast time + some fluff - 5 seconds or so
- a percentage of the spell's duration - 5 or 10% would be reasonable i think

**Comment by r33kgr3yj0y** [comment]
I agree with Kemaal. Maybe exclude Boon of the Legion and any buff that has a cooldown. No need to be tight with things like AA buffs or standard buffs, imo.

**Comment by RekkasGit** [comment]
This is a more difficult problem due to duration not being part of this netbots build, and needing to target to up to date times.  Probably going to need to work on passing buff slot information around the clients
